version: "3"
services:
  client:
    build: .
    # ports:
    # - 0.0.0.0:2001:80
    restart: unless-stopped
  
  swag:
    image: lscr.io/linuxserver/swag
    container_name: barlowdndswag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=dndbarlowproject.duckdns.org
      - DUCKDNSTOKEN = ${DUCKDNSTOKEN}
      - VALIDATION=duckdns
      - STAGING=true
    volumes:
      - /home/josh/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:2001:443
    restart: unless-stopped

  storage-api:
    image: jalapenojosh/storage-api-stormgate1998:latest
    container_name: dnd-storage-api
    volumes:
      - /home/josh/data/apiStorage:/app/storage
    restart: unless-stopped

  joshbarlowkeycloak:
    image: bitnami/keycloak:22
    container_name: joshbarlowkeycloak
    ports:
      - 2319:8080
    environment:
      - KEYCLOAK_DATABASE_PASSWORD=NoDefaults
      - KEYCLOAK_ADMIN_USER=user
      - KEYCLOAK_ADMIN_PASSWORD=bitnami
      - KEYCLOAK_DATABASE_HOST=joshkeycloakpostgresql
    command:
      - start
      - --proxy=edge
      - --hostname-strict=false
      - --hostname-strict-https=false
    restart: unless-stopped

  joshkeycloakpostgresql:
    image: postgres
    container_name: joshkeycloakpostgresql
    environment:
      - POSTGRES_USER=bn_keycloak
      - POSTGRES_PASSWORD=NoDefaults
      - POSTGRES_DB=bitnami_keycloak

    volumes:
      - /home/josh/data/kcpostgres:/var/lib/postgresql/data

    restart: unless-stopped

networks:
  default:
    external:
      name: keycloak-network