version: "3"
services:
  client:
    build: .
    # ports:
    # - 0.0.0.0:2001:80
    restart: unless-stopped
  
  swag:
    image: lscr.io/linuxserver/swag
    container_name: barlowdndswag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=dndbarlowproject.duckdns.org
      - DUCKDNSTOKEN = ${DUCKDNSTOKEN}
      - VALIDATION=duckdns
      - STAGING=true
    volumes:
      - /home/josh/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:2001:443
    restart: unless-stopped

  storage-api:
    image: jalapenojosh/storage-api-stormgate1998:latest
    container_name: josh-storage-api
    volumes:
      - /home/josh/data/apiStorage:/app/storage
    restart: unless-stopped